name: Rowboat Build

on:
  pull_request:

jobs:
  build-rowboat-nextjs:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: 'apps/rowboat/package-lock.json'
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        working-directory: apps/rowboat
        
      - name: Build Rowboat
        run: npm run build
        working-directory: apps/rowboat

  build-rowboatx:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v6
      
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          cache-dependency-path: 'apps/rowboat/package-lock.json'
          node-version: '24'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        working-directory: apps/cli
        
      - name: Build Rowboat
        run: npm run build
        working-directory: apps/cli 